put back env vars to allow cleaning of APT dirs

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -2,11 +2,42 @@
 # Floorspace specific build steps.
 # NOTE:  Must be the last build-pack on Heroku
 
-# Clean up
+# fail fast
+set -e
+
+# parse and derive params
+BUILD_DIR=$1
+CACHE_DIR=$2
+ENV_DIR=$3
+
+function error() {
+  echo " !     $*" >&2
+  exit 1
+}
+
+function topic() {
+  echo "-----> $*"
+}
+
+function indent() {
+  c='s/^/       /'
+  case $(uname) in
+    Darwin) sed -l "$c";;
+    *)      sed -u "$c";;
+  esac
+}
+
+
+# Clean up files to reduce SLUG size
 topic "Cleaning up unneunnecessary files"
 rm -rf $BUILD_DIR/static/*
 rm -rf $BUILD_DIR/staff/static/*
 rm -rf $BUILD_DIR/public/static/*
+
+# Clean up APT
+APT_CACHE_DIR="$CACHE_DIR/apt/cache"
+APT_STATE_DIR="$CACHE_DIR/apt/state"
+APT_OPTIONS="-o debug::nolocking=true -o dir::cache=$APT_CACHE_DIR -o dir::state=$APT_STATE_DIR"
 apt-get $APT_OPTIONS -y clean
 
 # Show the python environment
